# Generated by Django 4.2.17 on 2026-03-10 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("references", "0001_initial"),
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehousestock",
            name="asset",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="warehouse_stock",
                to="references.asset",
                verbose_name="Актив",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movements",
                to="references.asset",
                verbose_name="Актив",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="document_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
                verbose_name="Тип документа",
            ),
        ),
    ]
