# Generated by Django 4.2.17 on 2026-03-10 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("references", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="from_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movements_from",
                to=settings.AUTH_USER_MODEL,
                verbose_name="От кого",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="performed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="performed_movements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Выполнил",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="to_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movements_to",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кому",
            ),
        ),
        migrations.AddField(
            model_name="assetassignment",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="references.asset",
                verbose_name="Актив",
            ),
        ),
        migrations.AddField(
            model_name="assetassignment",
            name="assigned_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assignments_issued",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Выдал",
            ),
        ),
        migrations.AddField(
            model_name="assetassignment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_assignments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Сотрудник",
            ),
        ),
    ]
