# Generated by Django 4.2.17 on 2026-07-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehousestock",
            name="balance_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата остатка"),
        ),
    ]
