# Generated by Django 4.2.17 on 2026-07-14 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0006_asset_unit_of_measure_ref"),
        ("assets", "0004_warehousestock_balance_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetassignment",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="asset_assignments",
                to="references.warehouse",
                verbose_name="Склад",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_movements",
                to="references.warehouse",
                verbose_name="Склад",
            ),
        ),
        migrations.AddField(
            model_name="warehousestock",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_items",
                to="references.warehouse",
                verbose_name="Склад",
            ),
        ),
    ]
