# Generated by Django 4.2.17 on 2026-07-15 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0008_contract"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assets", "0006_seed_warehouse_links"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockAlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "threshold_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Критическое количество",
                    ),
                ),
                (
                    "message_template",
                    models.CharField(
                        blank=True,
                        default="{asset_name} на исходе, требуется срочное пополнение склада. Остаток: {quantity} {unit}.",
                        max_length=500,
                        verbose_name="Шаблон сообщения",
                    ),
                ),
                (
                    "assets",
                    models.ManyToManyField(
                        blank=True,
                        related_name="stock_alert_rules",
                        to="references.asset",
                        verbose_name="Индивидуальные товары",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="stock_alert_rules",
                        to="references.assetcategory",
                        verbose_name="Группы товаров",
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        related_name="stock_alert_rules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Получатели",
                    ),
                ),
                (
                    "warehouses",
                    models.ManyToManyField(
                        blank=True,
                        related_name="stock_alert_rules",
                        to="references.warehouse",
                        verbose_name="Склады",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройка аларма остатка",
                "verbose_name_plural": "Настройки алармов остатков",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StockAlertState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "current_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Текущее количество",
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, default="", verbose_name="Сообщение"),
                ),
                (
                    "triggered_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Сработало"),
                ),
                (
                    "last_notified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последнее уведомление"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Закрыто"),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="states",
                        to="assets.stockalertrule",
                        verbose_name="Правило",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_states",
                        to="assets.warehousestock",
                        verbose_name="Остаток",
                    ),
                ),
            ],
            options={
                "verbose_name": "Срабатывание аларма остатка",
                "verbose_name_plural": "Срабатывания алармов остатков",
                "ordering": ["-triggered_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="stockalertstate",
            constraint=models.UniqueConstraint(
                fields=("rule", "stock"), name="unique_stock_alert_rule_state"
            ),
        ),
    ]
