# Generated by Django 4.2.17 on 2026-03-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(max_length=254, verbose_name="Email получателя"),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="Тема")),
                (
                    "body_preview",
                    models.TextField(
                        blank=True, default="", verbose_name="Превью текста"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("SENT", "Отправлено"), ("FAILED", "Ошибка отправки")],
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Отправлено"),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, default="", verbose_name="Текст ошибки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Журнал email",
                "verbose_name_plural": "Журнал email",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("REQUEST_STATUS", "Изменение статуса заявки"),
                            ("DOCUMENT_TO_SIGN", "Документ на подписание"),
                            ("OVERDUE_TASK", "Просроченная задача"),
                            ("ASSET_EXPIRY", "Истечение срока актива"),
                            ("REMINDER", "Напоминание"),
                        ],
                        max_length=30,
                        verbose_name="Тип уведомления",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                (
                    "body",
                    models.TextField(blank=True, default="", verbose_name="Текст"),
                ),
                (
                    "related_object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ID связанного объекта"
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="Прочитано"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
                "ordering": ["-created_at"],
            },
        ),
    ]
