# Generated by Django 4.2.17 on 2026-07-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notification_type_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("REQUEST_STATUS", "Изменение статуса заявки"),
                    ("REQUEST_TO_APPROVE", "Заявка на согласование"),
                    ("REQUEST_TO_ISSUE", "Заявка на выдачу"),
                    ("DOCUMENT_TO_SIGN", "Документ на подписание"),
                    ("OVERDUE_TASK", "Просроченная задача"),
                    ("ASSET_EXPIRY", "Истечение срока актива"),
                    ("STOCK_ALERT", "Критический остаток"),
                    ("REMINDER", "Напоминание"),
                ],
                max_length=30,
                verbose_name="Тип уведомления",
            ),
        ),
    ]
