# Generated by Django 4.2.17 on 2026-07-13 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="PositionAccessRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(max_length=255, verbose_name="Должность"),
                ),
                (
                    "normalized_position",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=255,
                        verbose_name="Нормализованная должность",
                    ),
                ),
                (
                    "permission_code",
                    models.CharField(
                        choices=[
                            ("system.admin", "Администрирование системы"),
                            ("users.manage", "Управление сотрудниками"),
                            ("access.manage", "Управление правами"),
                            ("references.manage", "Редактирование справочников"),
                            ("requests.create", "Создание заявок"),
                            ("requests.view_all", "Просмотр всех заявок"),
                            (
                                "requests.approve_department",
                                "Согласование руководителем",
                            ),
                            ("requests.approve_ahs", "Согласование руководителем АХС"),
                            ("requests.issue", "Выдача по заявкам"),
                            ("warehouse.view", "Просмотр склада"),
                            ("warehouse.upload", "Импорт остатков склада"),
                            ("inventory.view_all", "Просмотр инвентарных карточек"),
                            ("documents.manage", "Работа с документами"),
                            ("reports.view", "Просмотр отчетов"),
                            ("integrations.sync", "Синхронизация 1С"),
                        ],
                        max_length=80,
                        verbose_name="Право",
                    ),
                ),
                (
                    "is_allowed",
                    models.BooleanField(default=True, verbose_name="Разрешено"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Право по должности",
                "verbose_name_plural": "Права по должностям",
                "ordering": ["position", "permission_code"],
            },
        ),
        migrations.CreateModel(
            name="UserAccessOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission_code",
                    models.CharField(
                        choices=[
                            ("system.admin", "Администрирование системы"),
                            ("users.manage", "Управление сотрудниками"),
                            ("access.manage", "Управление правами"),
                            ("references.manage", "Редактирование справочников"),
                            ("requests.create", "Создание заявок"),
                            ("requests.view_all", "Просмотр всех заявок"),
                            (
                                "requests.approve_department",
                                "Согласование руководителем",
                            ),
                            ("requests.approve_ahs", "Согласование руководителем АХС"),
                            ("requests.issue", "Выдача по заявкам"),
                            ("warehouse.view", "Просмотр склада"),
                            ("warehouse.upload", "Импорт остатков склада"),
                            ("inventory.view_all", "Просмотр инвентарных карточек"),
                            ("documents.manage", "Работа с документами"),
                            ("reports.view", "Просмотр отчетов"),
                            ("integrations.sync", "Синхронизация 1С"),
                        ],
                        max_length=80,
                        verbose_name="Право",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("GRANT", "Разрешить"), ("DENY", "Запретить")],
                        default="GRANT",
                        max_length=10,
                        verbose_name="Режим",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_overrides",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Индивидуальное право",
                "verbose_name_plural": "Индивидуальные права",
                "ordering": ["user__last_name", "user__first_name", "permission_code"],
            },
        ),
        migrations.AddConstraint(
            model_name="positionaccessrule",
            constraint=models.UniqueConstraint(
                fields=("normalized_position", "permission_code"),
                name="unique_position_access_rule",
            ),
        ),
        migrations.AddConstraint(
            model_name="useraccessoverride",
            constraint=models.UniqueConstraint(
                fields=("user", "permission_code"), name="unique_user_access_override"
            ),
        ),
    ]
