# Generated by Django 4.2.17 on 2026-07-14 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0006_asset_unit_of_measure_ref"),
        ("users", "0003_positionaccessrule_useraccessoverride_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="position_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="references.position",
                verbose_name="Должность из справочника",
            ),
        ),
    ]
