# Generated by Django 4.2.17 on 2026-07-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_seed_position_links"),
    ]

    operations = [
        migrations.AlterField(
            model_name="positionaccessrule",
            name="permission_code",
            field=models.CharField(
                choices=[
                    ("system.admin", "Администрирование системы"),
                    ("system.manager", "Статус управляющий"),
                    ("users.manage", "Управление сотрудниками"),
                    ("access.manage", "Управление правами"),
                    ("references.manage", "Редактирование справочников"),
                    ("requests.create", "Создание заявок"),
                    ("requests.view_all", "Просмотр всех заявок"),
                    ("requests.approve_department", "Согласование руководителем"),
                    ("requests.approve_ahs", "Согласование руководителем АХС"),
                    ("requests.issue", "Выдача по заявкам"),
                    ("warehouse.view", "Просмотр склада"),
                    ("warehouse.upload", "Импорт остатков склада"),
                    ("inventory.view_all", "Просмотр инвентарных карточек"),
                    ("documents.manage", "Работа с документами"),
                    ("reports.view", "Просмотр отчетов"),
                    ("integrations.sync", "Синхронизация 1С"),
                ],
                max_length=80,
                verbose_name="Право",
            ),
        ),
        migrations.AlterField(
            model_name="useraccessoverride",
            name="permission_code",
            field=models.CharField(
                choices=[
                    ("system.admin", "Администрирование системы"),
                    ("system.manager", "Статус управляющий"),
                    ("users.manage", "Управление сотрудниками"),
                    ("access.manage", "Управление правами"),
                    ("references.manage", "Редактирование справочников"),
                    ("requests.create", "Создание заявок"),
                    ("requests.view_all", "Просмотр всех заявок"),
                    ("requests.approve_department", "Согласование руководителем"),
                    ("requests.approve_ahs", "Согласование руководителем АХС"),
                    ("requests.issue", "Выдача по заявкам"),
                    ("warehouse.view", "Просмотр склада"),
                    ("warehouse.upload", "Импорт остатков склада"),
                    ("inventory.view_all", "Просмотр инвентарных карточек"),
                    ("documents.manage", "Работа с документами"),
                    ("reports.view", "Просмотр отчетов"),
                    ("integrations.sync", "Синхронизация 1С"),
                ],
                max_length=80,
                verbose_name="Право",
            ),
        ),
    ]
