/* tokens.ts — единый источник токенов дизайн-системы.
   Извлечён отдельно, чтобы избежать циклических зависимостей
   между primitives.tsx и компонентами в shared/ui/animated. */

export const C = {
  bg: '#F7F8FA',
  canvas: '#F7F8FA',
  white: '#FFFFFF',
  surface: '#FFFFFF',
  surfaceSolid: '#FFFFFF',
  surfaceSoft: '#FAFBFC',
  graphite: '#1B2A3D',
  graphiteSoft: '#243B55',
  graphiteMuted: '#8296AC',
  accent: '#0E7C86',
  accentDark: '#0B646C',
  accentCyan: '#0E7C86',
  accentLight: '#E7F2F3',
  accentSubtle: '#F2F8F8',
  teal: '#0E7C86',
  tealBg: '#E7F2F3',
  heading: '#1F2937',
  text: '#1F2937',
  secondary: '#64748B',
  muted: '#94A3B8',
  border: '#E5E7EB',
  rowBorder: '#EDEFF2',
  inputBorder: '#D6DAE0',
  hoverRow: '#F1F5F9',
  thBg: '#FAFBFC',
  danger: '#C4453D',
  dangerBg: '#FBEFEE',
  success: '#2F8F5B',
  successBg: '#EDF7F1',
  warning: '#C98A1E',
  warningBg: '#FBF4E7',
  info: '#0E7C86',
  infoBg: '#E7F2F3',
  tagBg: '#F1F5F9',
  glass: '#FFFFFF',
  glassStrong: '#FFFFFF',
  shadow: '0 8px 24px rgba(15, 23, 42, 0.12)',
  shadowSoft: 'none',
  shadowInset: 'none',
  radiusSm: 8,
  radiusMd: 10,
  radiusLg: 12,
  radiusXl: 12,
  spring: 'cubic-bezier(0, 0, 0.2, 1)',
  ease: 'cubic-bezier(0, 0, 0.2, 1)',
} as const;

export const statusColors: Record<string, { bg: string; color: string }> = {
  'В эксплуатации': { bg: C.successBg, color: C.success },
  'На ремонте': { bg: C.warningBg, color: C.warning },
  'Списано': { bg: C.tagBg, color: C.secondary },
  'Активна': { bg: C.successBg, color: C.success },
  'Активен': { bg: C.successBg, color: C.success },
  'Неактивен': { bg: C.tagBg, color: C.secondary },
  'Истекает': { bg: C.warningBg, color: C.warning },
  'На согласовании': { bg: C.infoBg, color: C.info },
  'Одобрена': { bg: C.successBg, color: C.success },
  'Выдано': { bg: C.tagBg, color: C.text },
  'Отклонена': { bg: C.dangerBg, color: C.danger },
  'Черновик': { bg: C.tagBg, color: C.secondary },
  'Исполнена': { bg: C.successBg, color: C.success },
  'Отменена': { bg: C.tagBg, color: C.secondary },
  'Действует': { bg: C.successBg, color: C.success },
  'Истёк': { bg: C.dangerBg, color: C.danger },
  DRAFT: { bg: C.tagBg, color: C.secondary },
  SENT_FOR_REVISION: { bg: C.warningBg, color: C.warning },
  PENDING_SUPERVISOR: { bg: C.infoBg, color: C.info },
  APPROVED_SUPERVISOR: { bg: C.infoBg, color: C.info },
  APPROVED_MOL: { bg: C.infoBg, color: C.info },
  APPROVED_AHS_HEAD: { bg: C.infoBg, color: C.info },
  APPROVED: { bg: C.successBg, color: C.success },
  EXECUTED: { bg: C.successBg, color: C.success },
  REJECTED: { bg: C.dangerBg, color: C.danger },
  CANCELLED: { bg: C.tagBg, color: C.secondary },
  ADMIN: { bg: C.dangerBg, color: C.danger },
  AHS_WORKER: { bg: C.infoBg, color: C.info },
  AHS_HEAD: { bg: '#F4F3FF', color: '#5925DC' },
  MOL_WAREHOUSE: { bg: C.successBg, color: C.success },
  MOL_NMA: { bg: C.tealBg, color: C.teal },
  FO_HEAD: { bg: C.warningBg, color: C.warning },
  DEPT_HEAD: { bg: C.infoBg, color: C.info },
  USER: { bg: C.tagBg, color: C.secondary },
  COMMISSION_MEMBER: { bg: '#FEF7C3', color: '#A15C07' },
  IRD_WORKER: { bg: '#FDF2FA', color: '#C11574' },
};
