# Generated by Django 4.2.17 on 2026-03-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssetRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        unique=True,
                        verbose_name="Номер заявки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Черновик"),
                            ("PENDING_SUPERVISOR", "На согласовании у руководителя"),
                            ("APPROVED_SUPERVISOR", "Согласована руководителем"),
                            ("APPROVED_MOL", "Согласована МОЛ"),
                            ("APPROVED_AHS_HEAD", "Утверждена руководителем АХС"),
                            ("APPROVED", "Утверждена"),
                            ("EXECUTED", "Исполнена"),
                            ("REJECTED", "Отклонена"),
                            ("CANCELLED", "Отменена"),
                        ],
                        default="DRAFT",
                        max_length=30,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, default="", verbose_name="Причина / обоснование"
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssetRequestItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_requested",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Запрошенное количество",
                    ),
                ),
                (
                    "quantity_issued",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Выданное количество",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, default="", verbose_name="Комментарий"
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция заявки",
                "verbose_name_plural": "Позиции заявки",
            },
        ),
        migrations.CreateModel(
            name="RequestApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_at_approval",
                    models.CharField(
                        max_length=30, verbose_name="Роль на момент согласования"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("APPROVED", "Согласовано"),
                            ("REJECTED", "Отклонено"),
                            ("SENT_TO_REVISION", "Отправлено на доработку"),
                        ],
                        max_length=20,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "otp_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="Хэш OTP-кода",
                    ),
                ),
                (
                    "otp_expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="OTP действует до"
                    ),
                ),
                (
                    "signed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Подписано"
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, default="", verbose_name="Комментарий"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
            ],
            options={
                "verbose_name": "Согласование заявки",
                "verbose_name_plural": "Согласования заявок",
                "ordering": ["-created_at"],
            },
        ),
    ]
