# Generated by Django 4.2.17 on 2026-03-10 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("references", "0002_initial"),
        ("requests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestapproval",
            name="approver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approvals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Согласующий",
            ),
        ),
        migrations.AddField(
            model_name="requestapproval",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approvals",
                to="requests.assetrequest",
                verbose_name="Заявка",
            ),
        ),
        migrations.AddField(
            model_name="assetrequestitem",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="request_items",
                to="references.asset",
                verbose_name="Актив",
            ),
        ),
        migrations.AddField(
            model_name="assetrequestitem",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="requests.assetrequest",
                verbose_name="Заявка",
            ),
        ),
        migrations.AddField(
            model_name="assetrequest",
            name="from_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requests_from",
                to=settings.AUTH_USER_MODEL,
                verbose_name="От кого (перемещение)",
            ),
        ),
        migrations.AddField(
            model_name="assetrequest",
            name="initiator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="initiated_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Инициатор",
            ),
        ),
        migrations.AddField(
            model_name="assetrequest",
            name="request_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requests",
                to="references.requesttype",
                verbose_name="Вид заявки",
            ),
        ),
        migrations.AddField(
            model_name="assetrequest",
            name="to_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requests_to",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кому (перемещение)",
            ),
        ),
    ]
