# Generated by Django 4.2.17 on 2026-07-02 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0004_approvalstep"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requestapproval",
            name="otp_code",
        ),
        migrations.RemoveField(
            model_name="requestapproval",
            name="otp_expires_at",
        ),
    ]
