# Generated by Django 4.2.17 on 2026-07-14 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("requests", "0006_issue_responsibles_and_workflow_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetrequest",
            name="deletion_requested_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата пометки на удаление"
            ),
        ),
        migrations.AddField(
            model_name="assetrequest",
            name="deletion_requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deletion_requested_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пометил на удаление",
            ),
        ),
    ]
