# Generated by Django 4.2.17 on 2026-07-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0007_assetrequest_deletion_requested_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetrequest",
            name="receipt_confirmed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Получение подтверждено"
            ),
        ),
        migrations.AlterField(
            model_name="assetrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Черновик"),
                    ("SENT_FOR_REVISION", "На корректировке"),
                    ("PENDING_SUPERVISOR", "На согласовании у руководителя"),
                    ("APPROVED_SUPERVISOR", "Согласована руководителем"),
                    ("APPROVED", "Согласована"),
                    ("PARTIALLY_ISSUED", "Частично выдана"),
                    ("EXECUTED", "Выдана"),
                    ("REJECTED", "Отклонена"),
                    ("CANCELLED", "Отменена"),
                ],
                default="DRAFT",
                max_length=30,
                verbose_name="Статус",
            ),
        ),
    ]
