# Generated by Django 4.2.17 on 2026-03-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                (
                    "code",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Код номенклатуры"
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("TMZ", "ТМЗ"),
                            ("OS", "ОС"),
                            ("NMA", "НМА"),
                            ("REPRESENTATIVE_TMZ", "Представительские ТМЗ"),
                        ],
                        max_length=20,
                        verbose_name="Тип актива",
                    ),
                ),
                (
                    "unit_of_measure",
                    models.CharField(max_length=50, verbose_name="Единица измерения"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Цена за единицу"
                    ),
                ),
                (
                    "is_long_term_use",
                    models.BooleanField(
                        default=False, verbose_name="ТМЗ длительного пользования"
                    ),
                ),
                (
                    "inventory_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Инвентарный номер",
                    ),
                ),
                (
                    "balance_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата постановки на баланс"
                    ),
                ),
                (
                    "useful_life_months",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Срок полезного использования (мес.)",
                    ),
                ),
                (
                    "depreciation_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Норма амортизации",
                    ),
                ),
                (
                    "source_1c_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="ID в 1С",
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последняя синхронизация"
                    ),
                ),
            ],
            options={
                "verbose_name": "Актив",
                "verbose_name_plural": "Активы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AssetCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Код"),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[("TMZ", "ТМЗ"), ("OS", "ОС"), ("NMA", "НМА")],
                        max_length=20,
                        verbose_name="Тип актива",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория актива",
                "verbose_name_plural": "Категории активов",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Counterparty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                (
                    "bin",
                    models.CharField(max_length=12, unique=True, verbose_name="БИН"),
                ),
                (
                    "address",
                    models.TextField(blank=True, default="", verbose_name="Адрес"),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Контактное лицо",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Телефон"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="Email"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Контрагент",
                "verbose_name_plural": "Контрагенты",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LimitNorm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[("TMZ", "ТМЗ"), ("OS", "ОС"), ("NMA", "НМА")],
                        max_length=20,
                        verbose_name="Тип актива",
                    ),
                ),
                (
                    "category",
                    models.CharField(max_length=255, verbose_name="Категория"),
                ),
                (
                    "quantity_limit",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Лимит количества"
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Ежемесячно"),
                            ("QUARTERLY", "Ежеквартально"),
                            ("ANNUAL", "Ежегодно"),
                        ],
                        max_length=20,
                        verbose_name="Период",
                    ),
                ),
                ("valid_from", models.DateField(verbose_name="Действует с")),
                ("valid_to", models.DateField(verbose_name="Действует до")),
            ],
            options={
                "verbose_name": "Лимит/норматив",
                "verbose_name_plural": "Лимиты и нормативы",
                "ordering": ["-valid_from"],
            },
        ),
        migrations.CreateModel(
            name="RequestType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Код"),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("TMZ", "ТМЗ"),
                            ("OS", "ОС"),
                            ("NMA", "НМА"),
                            ("REPRESENTATIVE_TMZ", "Представительские ТМЗ"),
                        ],
                        max_length=20,
                        verbose_name="Тип актива",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Описание"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Вид заявки",
                "verbose_name_plural": "Виды заявок",
                "ordering": ["name"],
            },
        ),
    ]
