# Generated by Django 4.2.17 on 2026-03-10 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("references", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="limitnorm",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_limits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создал",
            ),
        ),
        migrations.AddField(
            model_name="limitnorm",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="Если не указано — лимит на весь Фонд",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="limit_norms",
                to="users.department",
                verbose_name="Подразделение",
            ),
        ),
        migrations.AddField(
            model_name="assetcategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="references.assetcategory",
                verbose_name="Родительская категория",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assets",
                to="references.assetcategory",
                verbose_name="Категория",
            ),
        ),
    ]
