# Generated by Django 4.2.17 on 2026-07-14 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0005_unitofmeasure_warehouse_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="unit_of_measure_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assets",
                to="references.unitofmeasure",
                verbose_name="Единица измерения из справочника",
            ),
        ),
    ]
