# Generated by Django 4.2.17 on 2026-03-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(max_length=50, verbose_name="Тип синхронизации"),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Начало"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Окончание"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Выполняется"),
                            ("SUCCESS", "Успешно"),
                            ("FAILED", "Ошибка"),
                        ],
                        default="RUNNING",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_count",
                    models.IntegerField(default=0, verbose_name="Создано записей"),
                ),
                (
                    "updated_count",
                    models.IntegerField(default=0, verbose_name="Обновлено записей"),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, default="", verbose_name="Текст ошибки"
                    ),
                ),
                (
                    "is_stub",
                    models.BooleanField(default=True, verbose_name="Режим заглушки"),
                ),
            ],
            options={
                "verbose_name": "Журнал синхронизации",
                "verbose_name_plural": "Журнал синхронизации",
                "ordering": ["-started_at"],
            },
        ),
    ]
