# Generated by Django 4.2.17 on 2026-03-10 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommissionMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_label",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Роль в комиссии",
                    ),
                ),
            ],
            options={
                "verbose_name": "Член комиссии",
                "verbose_name_plural": "Члены комиссии",
            },
        ),
        migrations.CreateModel(
            name="CommissionProtocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Присваивается автоматически после финального подписания",
                        max_length=20,
                        verbose_name="Номер документа",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        help_text="Выставляется автоматически после финального подписания",
                        null=True,
                        verbose_name="Дата документа",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Черновик"),
                            ("PENDING_SIGNATURE", "На подписании"),
                            ("PARTIALLY_SIGNED", "Частично подписан"),
                            ("SIGNED", "Подписан"),
                            ("SENT_FOR_REVISION", "На доработке"),
                            ("CANCELLED", "Аннулирован"),
                        ],
                        default="DRAFT",
                        max_length=30,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "agenda_item",
                    models.TextField(
                        blank=True, default="", verbose_name="Пункт повестки дня"
                    ),
                ),
                (
                    "commission_order_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Номер приказа о комиссии",
                    ),
                ),
                (
                    "commission_order_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата приказа о комиссии"
                    ),
                ),
                (
                    "decision_text",
                    models.TextField(
                        blank=True, default="", verbose_name="Текст решения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Протокол заседания",
                "verbose_name_plural": "Протоколы заседаний",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentSignature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_id",
                    models.PositiveIntegerField(verbose_name="ID документа"),
                ),
                (
                    "role_label",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Роль при подписании",
                    ),
                ),
                (
                    "otp_code_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="Хэш OTP-кода",
                    ),
                ),
                (
                    "otp_expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="OTP действует до"
                    ),
                ),
                (
                    "signed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Подписано"
                    ),
                ),
                (
                    "is_acting_chairman",
                    models.BooleanField(
                        default=False, verbose_name="И.о. Председателя"
                    ),
                ),
                (
                    "sent_for_revision_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Отправлено на доработку"
                    ),
                ),
                (
                    "revision_reason",
                    models.TextField(
                        blank=True, default="", verbose_name="Причина возврата"
                    ),
                ),
            ],
            options={
                "verbose_name": "Подпись документа",
                "verbose_name_plural": "Подписи документов",
                "ordering": ["-signed_at"],
            },
        ),
        migrations.CreateModel(
            name="IncomingInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Присваивается автоматически после финального подписания",
                        max_length=20,
                        verbose_name="Номер документа",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        help_text="Выставляется автоматически после финального подписания",
                        null=True,
                        verbose_name="Дата документа",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Черновик"),
                            ("PENDING_SIGNATURE", "На подписании"),
                            ("PARTIALLY_SIGNED", "Частично подписан"),
                            ("SIGNED", "Подписан"),
                            ("SENT_FOR_REVISION", "На доработке"),
                            ("CANCELLED", "Аннулирован"),
                        ],
                        default="DRAFT",
                        max_length=30,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[("TMZ", "ТМЗ"), ("OS", "ОС"), ("NMA", "НМА")],
                        max_length=20,
                        verbose_name="Тип актива",
                    ),
                ),
            ],
            options={
                "verbose_name": "Приходная накладная",
                "verbose_name_plural": "Приходные накладные",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IncomingInvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Количество"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Цена за ед."
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Сумма"
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция накладной",
                "verbose_name_plural": "Позиции накладной",
            },
        ),
        migrations.CreateModel(
            name="InternalTransferInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Присваивается автоматически после финального подписания",
                        max_length=20,
                        verbose_name="Номер документа",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        help_text="Выставляется автоматически после финального подписания",
                        null=True,
                        verbose_name="Дата документа",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Черновик"),
                            ("PENDING_SIGNATURE", "На подписании"),
                            ("PARTIALLY_SIGNED", "Частично подписан"),
                            ("SIGNED", "Подписан"),
                            ("SENT_FOR_REVISION", "На доработке"),
                            ("CANCELLED", "Аннулирован"),
                        ],
                        default="DRAFT",
                        max_length=30,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[("OS", "ОС"), ("NMA", "НМА")],
                        max_length=20,
                        verbose_name="Тип актива",
                    ),
                ),
            ],
            options={
                "verbose_name": "Накладная на внутреннее перемещение",
                "verbose_name_plural": "Накладные на внутреннее перемещение",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InternalTransferItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Количество"
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция накладной перемещения",
                "verbose_name_plural": "Позиции накладной перемещения",
            },
        ),
        migrations.CreateModel(
            name="Petition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Присваивается автоматически после финального подписания",
                        max_length=20,
                        verbose_name="Номер документа",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        help_text="Выставляется автоматически после финального подписания",
                        null=True,
                        verbose_name="Дата документа",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Черновик"),
                            ("PENDING_SIGNATURE", "На подписании"),
                            ("PARTIALLY_SIGNED", "Частично подписан"),
                            ("SIGNED", "Подписан"),
                            ("SENT_FOR_REVISION", "На доработке"),
                            ("CANCELLED", "Аннулирован"),
                        ],
                        default="DRAFT",
                        max_length=30,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "legal_basis",
                    models.TextField(
                        blank=True, default="", verbose_name="Правовое основание"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ходатайство",
                "verbose_name_plural": "Ходатайства",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PetitionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Количество"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Цена за ед."
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Сумма"
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция ходатайства",
                "verbose_name_plural": "Позиции ходатайства",
            },
        ),
        migrations.CreateModel(
            name="ProtocolItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Количество"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Цена за ед."
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Сумма"
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция приложения к протоколу",
                "verbose_name_plural": "Позиции приложения к протоколу",
            },
        ),
        migrations.CreateModel(
            name="WriteOffAct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Присваивается автоматически после финального подписания",
                        max_length=20,
                        verbose_name="Номер документа",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        help_text="Выставляется автоматически после финального подписания",
                        null=True,
                        verbose_name="Дата документа",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Черновик"),
                            ("PENDING_SIGNATURE", "На подписании"),
                            ("PARTIALLY_SIGNED", "Частично подписан"),
                            ("SIGNED", "Подписан"),
                            ("SENT_FOR_REVISION", "На доработке"),
                            ("CANCELLED", "Аннулирован"),
                        ],
                        default="DRAFT",
                        max_length=30,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "act_type",
                    models.CharField(
                        choices=[
                            ("TMZ", "Списание ТМЗ"),
                            ("REPRESENTATIVE_TMZ", "Списание представительских ТМЗ"),
                            ("OS_NMA", "Списание ОС/НМА"),
                            ("DESTRUCTION", "Акт уничтожения"),
                        ],
                        max_length=30,
                        verbose_name="Тип акта",
                    ),
                ),
                (
                    "commission_order_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Номер приказа о комиссии",
                    ),
                ),
                (
                    "commission_order_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата приказа о комиссии"
                    ),
                ),
                (
                    "is_representative",
                    models.BooleanField(
                        default=False, verbose_name="Представительские расходы"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Итого сумма",
                    ),
                ),
            ],
            options={
                "verbose_name": "Акт на списание",
                "verbose_name_plural": "Акты на списание",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WriteOffActItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Количество"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Цена за ед."
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Сумма"
                    ),
                ),
                (
                    "act",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="documents.writeoffact",
                        verbose_name="Акт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция акта списания",
                "verbose_name_plural": "Позиции акта списания",
            },
        ),
    ]
