# Generated by Django 4.2.17 on 2026-03-10 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        ("references", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="writeoffactitem",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="write_off_items",
                to="references.asset",
                verbose_name="Актив",
            ),
        ),
    ]
