# Generated by Django 4.2.17 on 2026-07-02 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentsignature",
            name="otp_code_hash",
        ),
        migrations.RemoveField(
            model_name="documentsignature",
            name="otp_expires_at",
        ),
    ]
