# Generated by Django 4.2.17 on 2026-07-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_remove_documentsignature_otp_code_hash_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commissionprotocol",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Черновик"),
                    ("PENDING_AHS_APPROVAL", "На согласовании у руководителя АХС"),
                    ("PENDING_SIGNATURE", "На подписании"),
                    ("PARTIALLY_SIGNED", "Частично подписан"),
                    ("SIGNED", "Подписан"),
                    ("SENT_FOR_REVISION", "На доработке"),
                    ("REJECTED", "Отклонён"),
                    ("CANCELLED", "Аннулирован"),
                ],
                default="DRAFT",
                max_length=30,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="incominginvoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Черновик"),
                    ("PENDING_AHS_APPROVAL", "На согласовании у руководителя АХС"),
                    ("PENDING_SIGNATURE", "На подписании"),
                    ("PARTIALLY_SIGNED", "Частично подписан"),
                    ("SIGNED", "Подписан"),
                    ("SENT_FOR_REVISION", "На доработке"),
                    ("REJECTED", "Отклонён"),
                    ("CANCELLED", "Аннулирован"),
                ],
                default="DRAFT",
                max_length=30,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="internaltransferinvoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Черновик"),
                    ("PENDING_AHS_APPROVAL", "На согласовании у руководителя АХС"),
                    ("PENDING_SIGNATURE", "На подписании"),
                    ("PARTIALLY_SIGNED", "Частично подписан"),
                    ("SIGNED", "Подписан"),
                    ("SENT_FOR_REVISION", "На доработке"),
                    ("REJECTED", "Отклонён"),
                    ("CANCELLED", "Аннулирован"),
                ],
                default="DRAFT",
                max_length=30,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="petition",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Черновик"),
                    ("PENDING_AHS_APPROVAL", "На согласовании у руководителя АХС"),
                    ("PENDING_SIGNATURE", "На подписании"),
                    ("PARTIALLY_SIGNED", "Частично подписан"),
                    ("SIGNED", "Подписан"),
                    ("SENT_FOR_REVISION", "На доработке"),
                    ("REJECTED", "Отклонён"),
                    ("CANCELLED", "Аннулирован"),
                ],
                default="DRAFT",
                max_length=30,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="writeoffact",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Черновик"),
                    ("PENDING_AHS_APPROVAL", "На согласовании у руководителя АХС"),
                    ("PENDING_SIGNATURE", "На подписании"),
                    ("PARTIALLY_SIGNED", "Частично подписан"),
                    ("SIGNED", "Подписан"),
                    ("SENT_FOR_REVISION", "На доработке"),
                    ("REJECTED", "Отклонён"),
                    ("CANCELLED", "Аннулирован"),
                ],
                default="DRAFT",
                max_length=30,
                verbose_name="Статус",
            ),
        ),
    ]
