# Generated by Django 4.2.17 on 2026-07-15 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0008_contract"),
        ("documents", "0005_alter_commissionprotocol_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incominginvoice",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incoming_invoices",
                to="references.warehouse",
                verbose_name="Склад",
            ),
        ),
        migrations.AlterField(
            model_name="commissionprotocol",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Черновик"),
                    ("PENDING_AHS_APPROVAL", "На согласовании у руководителя АХС"),
                    ("PENDING_CHANGE_APPROVAL", "Запрошено изменение"),
                    ("PENDING_SIGNATURE", "На подписании"),
                    ("PARTIALLY_SIGNED", "Частично подписан"),
                    ("SIGNED", "Подписан"),
                    ("SENT_FOR_REVISION", "На доработке"),
                    ("REJECTED", "Отклонён"),
                    ("CANCELLED", "Аннулирован"),
                ],
                default="DRAFT",
                max_length=30,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="incominginvoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Черновик"),
                    ("PENDING_AHS_APPROVAL", "На согласовании у руководителя АХС"),
                    ("PENDING_CHANGE_APPROVAL", "Запрошено изменение"),
                    ("PENDING_SIGNATURE", "На подписании"),
                    ("PARTIALLY_SIGNED", "Частично подписан"),
                    ("SIGNED", "Подписан"),
                    ("SENT_FOR_REVISION", "На доработке"),
                    ("REJECTED", "Отклонён"),
                    ("CANCELLED", "Аннулирован"),
                ],
                default="DRAFT",
                max_length=30,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="internaltransferinvoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Черновик"),
                    ("PENDING_AHS_APPROVAL", "На согласовании у руководителя АХС"),
                    ("PENDING_CHANGE_APPROVAL", "Запрошено изменение"),
                    ("PENDING_SIGNATURE", "На подписании"),
                    ("PARTIALLY_SIGNED", "Частично подписан"),
                    ("SIGNED", "Подписан"),
                    ("SENT_FOR_REVISION", "На доработке"),
                    ("REJECTED", "Отклонён"),
                    ("CANCELLED", "Аннулирован"),
                ],
                default="DRAFT",
                max_length=30,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="petition",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Черновик"),
                    ("PENDING_AHS_APPROVAL", "На согласовании у руководителя АХС"),
                    ("PENDING_CHANGE_APPROVAL", "Запрошено изменение"),
                    ("PENDING_SIGNATURE", "На подписании"),
                    ("PARTIALLY_SIGNED", "Частично подписан"),
                    ("SIGNED", "Подписан"),
                    ("SENT_FOR_REVISION", "На доработке"),
                    ("REJECTED", "Отклонён"),
                    ("CANCELLED", "Аннулирован"),
                ],
                default="DRAFT",
                max_length=30,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="writeoffact",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Черновик"),
                    ("PENDING_AHS_APPROVAL", "На согласовании у руководителя АХС"),
                    ("PENDING_CHANGE_APPROVAL", "Запрошено изменение"),
                    ("PENDING_SIGNATURE", "На подписании"),
                    ("PARTIALLY_SIGNED", "Частично подписан"),
                    ("SIGNED", "Подписан"),
                    ("SENT_FOR_REVISION", "На доработке"),
                    ("REJECTED", "Отклонён"),
                    ("CANCELLED", "Аннулирован"),
                ],
                default="DRAFT",
                max_length=30,
                verbose_name="Статус",
            ),
        ),
    ]
