# -*- coding: utf-8 -*-
"""Данные для генерации описания базы данных ИС «АСУ» (docx)."""

# Каждая таблица: (имя_таблицы, назначение, [(поле, тип, описание), ...])

ORG_TABLES = [
    ("users_department", "Подразделения организации с поддержкой иерархии.", [
        ("id", "bigint PK", "Первичный ключ."),
        ("name", "varchar(255)", "Наименование подразделения."),
        ("code", "varchar(50), unique", "Уникальный код подразделения."),
        ("head_id", "FK → users_user, SET_NULL", "Руководитель подразделения."),
        ("parent_id", "FK → users_department, SET_NULL", "Родительское подразделение (иерархия)."),
    ]),
    ("users_user", "Пользователи системы. Расширяет стандартную модель Django (AbstractUser): к логину, паролю, email и флагам добавлены корпоративные атрибуты.", [
        ("id", "bigint PK", "Первичный ключ."),
        ("username", "varchar(150), unique", "Логин пользователя."),
        ("password", "varchar(128)", "Хеш пароля (PBKDF2)."),
        ("first_name / last_name", "varchar(150)", "Имя и фамилия."),
        ("patronymic", "varchar(150)", "Отчество."),
        ("email", "varchar(254)", "Электронная почта."),
        ("photo", "varchar (ImageField)", "Фотография профиля (users/photos/)."),
        ("position", "varchar(255)", "Должность (текст, синхронизируется со справочником)."),
        ("position_ref_id", "FK → references_position, SET_NULL", "Должность из справочника. При сохранении текстовое поле position автоматически принимает её название."),
        ("department_id", "FK → users_department, SET_NULL", "Подразделение сотрудника."),
        ("phone", "varchar(20)", "Телефон."),
        ("role", "varchar(30), choices", "Системная роль: ADMIN, AHS_WORKER, AHS_HEAD, MOL_WAREHOUSE, MOL_NMA, DEPT_HEAD, USER и др."),
        ("supervisor_id", "FK → users_user, SET_NULL", "Непосредственный руководитель (для маршрутизации согласований)."),
        ("is_active / is_staff / is_superuser", "boolean", "Стандартные флаги Django."),
        ("date_joined / last_login", "timestamp", "Служебные отметки времени."),
    ]),
    ("references_position", "Справочник должностей. При переименовании должности автоматически обновляются карточки сотрудников и правила прав по должностям.", [
        ("id", "bigint PK", "Первичный ключ."),
        ("name", "varchar(255), unique", "Наименование должности."),
        ("code", "varchar(50), unique", "Код должности."),
        ("is_active", "boolean", "Признак активности."),
        ("created_at / updated_at", "timestamp", "Метки времени (TimestampMixin)."),
    ]),
    ("users_positionaccessrule", "Правила прав, применяемые ко всем сотрудникам с одинаковой должностью.", [
        ("id", "bigint PK", "Первичный ключ."),
        ("position", "varchar(255)", "Должность в исходном написании."),
        ("normalized_position", "varchar(255), indexed", "Нормализованное название (заполняется автоматически, служит ключом сопоставления)."),
        ("permission_code", "varchar(80), choices", "Код права (system.admin, users.manage, references.manage и т.д.)."),
        ("is_allowed", "boolean", "Разрешение (true) или запрет (false)."),
        ("is_active", "boolean", "Признак активности правила."),
        ("comment", "varchar(255)", "Комментарий администратора."),
        ("created_at / updated_at", "timestamp", "Метки времени."),
    ]),
    ("users_useraccessoverride", "Индивидуальные разрешения или запреты для конкретного сотрудника. Приоритетнее правил по должности.", [
        ("id", "bigint PK", "Первичный ключ."),
        ("user_id", "FK → users_user, CASCADE", "Пользователь."),
        ("permission_code", "varchar(80), choices", "Код права."),
        ("mode", "varchar(10): GRANT / DENY", "Режим: разрешить или запретить."),
        ("comment", "varchar(255)", "Комментарий."),
        ("created_at / updated_at", "timestamp", "Метки времени."),
    ]),
]

REF_TABLES = [
    ("references_counterparty", "Контрагенты (поставщики).", [
        ("id", "bigint PK", "Первичный ключ."),
        ("name", "varchar(255)", "Наименование."),
        ("bin", "varchar(12), unique", "БИН — бизнес-идентификационный номер, уникален."),
        ("address", "text", "Юридический адрес."),
        ("contact_person", "varchar(255)", "Контактное лицо."),
        ("phone / email", "varchar(20) / varchar(254)", "Контактные данные."),
        ("is_active", "boolean", "Признак активности."),
        ("created_at / updated_at", "timestamp", "Метки времени."),
    ]),
    ("references_contract", "Договоры с контрагентами, включая PDF-файл. Удаляются каскадно вместе с контрагентом.", [
        ("id", "bigint PK", "Первичный ключ."),
        ("name", "varchar(255)", "Наименование договора."),
        ("contract_date", "date", "Дата договора."),
        ("valid_until", "date", "Срок действия."),
        ("counterparty_id", "FK → references_counterparty, CASCADE", "Контрагент."),
        ("pdf_file", "varchar (FileField)", "PDF-файл договора (contracts/pdfs/)."),
        ("created_at / updated_at", "timestamp", "Метки времени."),
    ]),
    ("references_requesttype", "Виды заявок. Определяют тип актива и настраиваемый маршрут согласования.", [
        ("id", "bigint PK", "Первичный ключ."),
        ("name", "varchar(255)", "Наименование."),
        ("code", "varchar(50), unique", "Уникальный код."),
        ("asset_type", "varchar(20), choices", "Тип актива: TMZ, OS, NMA, REPRESENTATIVE_TMZ."),
        ("requires_long_term_use", "boolean", "Только номенклатура длительного пользования (для ТМЗ)."),
        ("description", "text", "Описание."),
        ("is_active", "boolean", "Признак активности."),
    ]),
    ("references_assetcategory", "Категории и группы активов. Иерархия через parent_id: верхний уровень — категория, вложенный — группа.", [
        ("id", "bigint PK", "Первичный ключ."),
        ("name", "varchar(255)", "Наименование."),
        ("code", "varchar(50), unique", "Уникальный код."),
        ("asset_type", "varchar(20), choices", "Базовый тип актива: TMZ, OS, NMA."),
        ("parent_id", "FK → references_assetcategory, SET_NULL", "Родительская категория."),
    ]),
    ("references_unitofmeasure", "Единицы измерения. При переименовании автоматически обновляется текстовое поле в карточках активов.", [
        ("id", "bigint PK", "Первичный ключ."),
        ("name", "varchar(255), unique", "Наименование (шт., кг, л и т.д.)."),
        ("code", "varchar(50), unique", "Код."),
        ("is_active", "boolean", "Признак активности."),
        ("created_at / updated_at", "timestamp", "Метки времени."),
    ]),
    ("references_warehouse", "Склады и места хранения. Привязаны к подразделению-владельцу.", [
        ("id", "bigint PK", "Первичный ключ."),
        ("name", "varchar(255)", "Наименование склада."),
        ("code", "varchar(50), unique", "Код склада."),
        ("department_id", "FK → users_department, SET_NULL", "Подразделение-владелец."),
        ("address", "varchar(255)", "Адрес."),
        ("is_active", "boolean", "Признак активности."),
        ("created_at / updated_at", "timestamp", "Метки времени."),
    ]),
    ("references_limitnorm", "Лимиты и нормативы выдачи по категориям. Могут действовать на весь Фонд или на конкретное подразделение.", [
        ("id", "bigint PK", "Первичный ключ."),
        ("asset_type", "varchar(20), choices", "Тип актива."),
        ("category", "varchar(255)", "Категория, к которой применяется лимит."),
        ("quantity_limit", "decimal(12,2)", "Лимит количества."),
        ("period", "varchar(20), choices", "Период действия лимита (месяц, квартал, год)."),
        ("department_id", "FK → users_department, SET_NULL", "Подразделение; пусто — лимит на весь Фонд."),
        ("valid_from / valid_to", "date", "Период действия."),
        ("created_by_id", "FK → users_user, SET_NULL", "Автор записи."),
        ("created_at / updated_at", "timestamp", "Метки времени."),
    ]),
    ("references_asset", "Универсальная карточка актива для ТМЗ, ОС, НМА и представительских ТМЗ. Центральная сущность номенклатуры.", [
        ("id", "bigint PK", "Первичный ключ."),
        ("name", "varchar(255)", "Наименование."),
        ("code", "varchar(100), unique", "Код номенклатуры (генерируется с префиксом по типу актива)."),
        ("asset_type", "varchar(20), choices", "TMZ / OS / NMA / REPRESENTATIVE_TMZ."),
        ("category_id", "FK → references_assetcategory, PROTECT", "Категория (обязательная, защищена от удаления)."),
        ("group_id", "FK → references_assetcategory, SET_NULL", "Группа (вложенная категория)."),
        ("unit_of_measure", "varchar(50)", "Единица измерения (текст, синхронизируется со справочником)."),
        ("unit_of_measure_ref_id", "FK → references_unitofmeasure, PROTECT", "Единица измерения из справочника."),
        ("unit_price", "decimal(15,2)", "Цена за единицу."),
        ("is_long_term_use", "boolean", "ТМЗ длительного пользования."),
        ("inventory_number", "varchar(100)", "Инвентарный номер (для ОС/НМА)."),
        ("balance_date", "date", "Дата постановки на баланс."),
        ("useful_life_months", "int", "Срок полезного использования, месяцев."),
        ("depreciation_rate", "decimal(5,2)", "Норма амортизации."),
        ("source_1c_id", "varchar(100), unique", "Внешний идентификатор в 1С (ключ интеграции)."),
        ("last_sync_at", "timestamp", "Последняя синхронизация с 1С."),
        ("created_at / updated_at", "timestamp", "Метки времени."),
    ]),
]

STOCK_TABLES = [
    ("assets_warehousestock", "Текущий остаток по активу. Связь с активом — один к одному: одна строка остатка на одну карточку.", [
        ("id", "bigint PK", "Первичный ключ."),
        ("asset_id", "OneToOne → references_asset, CASCADE", "Актив (уникальная связь)."),
        ("quantity", "decimal(12,2)", "Текущее количество."),
        ("total_amount", "decimal(15,2)", "Общая сумма (количество × цена)."),
        ("balance_date", "date", "Дата остатка."),
        ("warehouse_id", "FK → references_warehouse, SET_NULL", "Склад хранения."),
        ("location", "varchar(255)", "Место хранения (автозаполняется названием склада)."),
        ("created_at / updated_at", "timestamp", "Метки времени."),
    ]),
    ("assets_stockmovement", "Журнал всех складских операций — аудиторская история движения активов.", [
        ("id", "bigint PK", "Первичный ключ."),
        ("asset_id", "FK → references_asset, CASCADE", "Актив."),
        ("movement_type", "varchar(30), choices", "Тип операции: RECEIPT (приход), ISSUE (выдача), TRANSFER (перемещение), WRITE_OFF (списание) и др."),
        ("quantity", "decimal(12,2)", "Количество."),
        ("unit_price", "decimal(15,2)", "Цена за единицу на момент операции."),
        ("total_amount", "decimal(15,2)", "Сумма (рассчитывается автоматически)."),
        ("from_user_id / to_user_id", "FK → users_user, SET_NULL", "Стороны операции."),
        ("document_type_id + document_id", "GenericFK → ContentType", "Полиморфная ссылка на документ-основание (накладную, акт и т.д.)."),
        ("performed_by_id", "FK → users_user, SET_NULL", "Исполнитель операции."),
        ("performed_at", "timestamp", "Дата и время операции."),
        ("warehouse_id", "FK → references_warehouse, SET_NULL", "Склад операции."),
        ("comment", "text", "Комментарий."),
    ]),
    ("assets_assetassignment", "Закрепление ОС/НМА/ТМЗ длительного пользования за сотрудником.", [
        ("id", "bigint PK", "Первичный ключ."),
        ("asset_id", "FK → references_asset, CASCADE", "Актив."),
        ("user_id", "FK → users_user, CASCADE", "Сотрудник, за которым закреплён актив."),
        ("quantity", "decimal(12,2)", "Количество."),
        ("assigned_at", "timestamp", "Дата выдачи."),
        ("assigned_by_id", "FK → users_user, SET_NULL", "Кто выдал."),
        ("warehouse_id", "FK → references_warehouse, SET_NULL", "Склад выдачи."),
        ("location", "varchar(255)", "Местоположение."),
        ("status", "varchar(20), choices", "ACTIVE (закреплён), RETURNED (возвращён), WRITTEN_OFF (списан)."),
    ]),
    ("assets_stockalertrule", "Правила контроля критических остатков. Область действия задаётся M2M-связями: получатели, группы, отдельные товары, склады.", [
        ("id", "bigint PK", "Первичный ключ."),
        ("name", "varchar(255)", "Наименование правила."),
        ("is_active", "boolean", "Признак активности."),
        ("threshold_quantity", "decimal(12,2)", "Пороговое (критическое) количество."),
        ("recipients", "M2M → users_user", "Получатели уведомлений."),
        ("groups", "M2M → references_assetcategory", "Контролируемые группы товаров."),
        ("assets", "M2M → references_asset", "Индивидуальные контролируемые товары."),
        ("warehouses", "M2M → references_warehouse", "Контролируемые склады."),
        ("message_template", "varchar(500)", "Шаблон текста уведомления с плейсхолдерами {asset_name}, {quantity}, {unit}."),
        ("created_at / updated_at", "timestamp", "Метки времени."),
    ]),
    ("assets_stockalertstate", "Срабатывания правил контроля остатков. Уникальность: одно активное срабатывание на пару «правило + остаток».", [
        ("id", "bigint PK", "Первичный ключ."),
        ("rule_id", "FK → assets_stockalertrule, CASCADE", "Правило."),
        ("stock_id", "FK → assets_warehousestock, CASCADE", "Контролируемый остаток."),
        ("is_active", "boolean", "Аларм активен."),
        ("current_quantity", "decimal(12,2)", "Количество на момент срабатывания."),
        ("message", "text", "Сформированное сообщение."),
        ("triggered_at", "timestamp", "Момент срабатывания."),
        ("last_notified_at", "timestamp", "Последнее уведомление."),
        ("resolved_at", "timestamp", "Момент закрытия (после пополнения)."),
    ]),
]

REQUEST_TABLES = [
    ("requests_assetrequest", "Заголовок заявки на выдачу, перемещение или изменение активов. Номер формата NNN/ГГГГ присваивается автоматически.", [
        ("id", "bigint PK", "Первичный ключ."),
        ("number", "varchar(20), unique", "Номер заявки (например, 012/2026)."),
        ("request_type_id", "FK → references_requesttype, PROTECT", "Вид заявки."),
        ("status", "varchar(30), choices", "Статус workflow (см. схему статусов)."),
        ("initiator_id", "FK → users_user, CASCADE", "Инициатор заявки."),
        ("from_user_id / to_user_id", "FK → users_user, SET_NULL", "Стороны при перемещении."),
        ("reason", "text", "Причина / обоснование."),
        ("issue_responsibles", "M2M → users_user", "Ответственные за выдачу (назначает руководитель АХС)."),
        ("deletion_requested_by_id", "FK → users_user, SET_NULL", "Кто пометил заявку на удаление."),
        ("deletion_requested_at", "timestamp", "Момент пометки на удаление."),
        ("created_at / updated_at", "timestamp", "Метки времени."),
    ]),
    ("requests_assetrequestitem", "Позиции заявки. Могут ссылаться на конкретный актив или на запрошенную группу (сценарий «интернет-магазина»).", [
        ("id", "bigint PK", "Первичный ключ."),
        ("request_id", "FK → requests_assetrequest, CASCADE", "Заявка."),
        ("requested_group_id", "FK → references_assetcategory, PROTECT", "Запрошенная группа (если товар не конкретизирован)."),
        ("asset_id", "FK → references_asset, PROTECT", "Запрошенный актив."),
        ("issued_asset_id", "FK → references_asset, PROTECT", "Фактически выданный актив (может отличаться от запрошенного)."),
        ("quantity_requested", "decimal(12,2)", "Запрошенное количество."),
        ("quantity_issued", "decimal(12,2)", "Фактически выданное количество."),
        ("comment", "text", "Комментарий."),
    ]),
    ("requests_requestapproval", "Журнал согласований и подписаний заявки — полная история переходов.", [
        ("id", "bigint PK", "Первичный ключ."),
        ("request_id", "FK → requests_assetrequest, CASCADE", "Заявка."),
        ("approver_id", "FK → users_user, CASCADE", "Согласующий."),
        ("role_at_approval", "varchar(30)", "Роль согласующего на момент действия."),
        ("action", "varchar(20), choices", "Действие: APPROVE, REJECT, REVISION и др."),
        ("signed_at", "timestamp", "Момент подписания."),
        ("comment", "text", "Комментарий согласующего."),
        ("created_at", "timestamp", "Момент записи."),
    ]),
    ("requests_approvalstep", "Настраиваемые этапы маршрута согласования по каждому виду заявки. Уникальность: вид заявки + порядок.", [
        ("id", "bigint PK", "Первичный ключ."),
        ("request_type_id", "FK → references_requesttype, CASCADE", "Вид заявки."),
        ("order", "int", "Порядковый номер этапа."),
        ("approver_role", "varchar(30), choices", "Роль согласующего на этапе."),
        ("title", "varchar(255)", "Наименование этапа."),
        ("requires_supervisor", "boolean", "Согласует только непосредственный руководитель инициатора."),
        ("is_active", "boolean", "Признак активности."),
    ]),
]

DOC_TABLES = [
    ("documents_incominginvoice", "Приходная накладная — поступление активов от контрагента на склад.", [
        ("id", "bigint PK", "Первичный ключ."),
        ("number / date / status / created_by_id", "общие поля BaseDocument", "См. описание общих полей документов."),
        ("asset_type", "varchar(20), choices", "Тип поступающих активов: TMZ / OS / NMA."),
        ("counterparty_id", "FK → references_counterparty, PROTECT", "Поставщик."),
        ("mol_warehouse_id", "FK → users_user, SET_NULL", "Материально ответственное лицо."),
        ("warehouse_id", "FK → references_warehouse, PROTECT", "Склад приёмки."),
    ]),
    ("documents_incominginvoiceitem", "Позиции приходной накладной. Сумма рассчитывается автоматически.", [
        ("id", "bigint PK", "Первичный ключ."),
        ("invoice_id", "FK → documents_incominginvoice, CASCADE", "Накладная."),
        ("asset_id", "FK → references_asset, PROTECT", "Актив."),
        ("quantity / unit_price / total", "decimal", "Количество, цена, сумма (total = quantity × unit_price)."),
    ]),
    ("documents_writeoffact", "Акт на списание ТМЗ / ОС / НМА, в том числе представительских расходов.", [
        ("id", "bigint PK", "Первичный ключ."),
        ("number / date / status / created_by_id", "общие поля BaseDocument", "См. описание общих полей документов."),
        ("act_type", "varchar(30), choices", "Тип акта списания."),
        ("commission_order_number / commission_order_date", "varchar(50) / date", "Реквизиты приказа о комиссии."),
        ("is_representative", "boolean", "Представительские расходы."),
        ("total_amount", "decimal(15,2)", "Итоговая сумма (пересчитывается по позициям)."),
    ]),
    ("documents_writeoffactitem", "Позиции акта на списание.", [
        ("id", "bigint PK", "Первичный ключ."),
        ("act_id", "FK → documents_writeoffact, CASCADE", "Акт."),
        ("asset_id", "FK → references_asset, PROTECT", "Актив."),
        ("quantity / unit_price / total", "decimal", "Количество, цена, сумма."),
    ]),
    ("documents_petition", "Ходатайство на выбытие ОС/НМА — инициирующий документ процедуры списания основных средств.", [
        ("id", "bigint PK", "Первичный ключ."),
        ("number / date / status / created_by_id", "общие поля BaseDocument", "См. описание общих полей документов."),
        ("legal_basis", "text", "Правовое основание."),
    ]),
    ("documents_petitionitem", "Позиции ходатайства.", [
        ("id", "bigint PK", "Первичный ключ."),
        ("petition_id", "FK → documents_petition, CASCADE", "Ходатайство."),
        ("asset_id", "FK → references_asset, PROTECT", "Актив."),
        ("quantity / unit_price / total", "decimal", "Количество, цена, сумма."),
    ]),
    ("documents_commissionprotocol", "Протокол заседания Рабочей комиссии. Может ссылаться на ходатайство-основание.", [
        ("id", "bigint PK", "Первичный ключ."),
        ("number / date / status / created_by_id", "общие поля BaseDocument", "См. описание общих полей документов."),
        ("petition_id", "FK → documents_petition, SET_NULL", "Ходатайство-основание."),
        ("agenda_item", "text", "Пункт повестки дня."),
        ("commission_order_number / commission_order_date", "varchar(50) / date", "Реквизиты приказа о комиссии."),
        ("decision_text", "text", "Текст решения комиссии."),
    ]),
    ("documents_protocolitem", "Позиции приложения к протоколу (Приложение 1).", [
        ("id", "bigint PK", "Первичный ключ."),
        ("protocol_id", "FK → documents_commissionprotocol, CASCADE", "Протокол."),
        ("asset_id", "FK → references_asset, PROTECT", "Актив."),
        ("quantity / unit_price / total", "decimal", "Количество, цена, сумма."),
    ]),
    ("documents_internaltransferinvoice", "Накладная на внутреннее перемещение ОС/НМА между сотрудниками.", [
        ("id", "bigint PK", "Первичный ключ."),
        ("number / date / status / created_by_id", "общие поля BaseDocument", "См. описание общих полей документов."),
        ("from_user_id / to_user_id", "FK → users_user, SET_NULL", "Передающая и принимающая стороны."),
        ("asset_type", "varchar(20): OS / NMA", "Тип перемещаемых активов."),
    ]),
    ("documents_internaltransferitem", "Позиции накладной на внутреннее перемещение.", [
        ("id", "bigint PK", "Первичный ключ."),
        ("invoice_id", "FK → documents_internaltransferinvoice, CASCADE", "Накладная."),
        ("asset_id", "FK → references_asset, PROTECT", "Актив."),
        ("quantity", "decimal(12,2)", "Количество."),
    ]),
    ("documents_commissionmember", "Члены комиссии для актов, ходатайств и протоколов (одна таблица на три типа документов).", [
        ("id", "bigint PK", "Первичный ключ."),
        ("user_id", "FK → users_user, CASCADE", "Сотрудник — член комиссии."),
        ("write_off_act_id", "FK → documents_writeoffact, CASCADE", "Акт списания (если применимо)."),
        ("petition_id", "FK → documents_petition, CASCADE", "Ходатайство (если применимо)."),
        ("protocol_id", "FK → documents_commissionprotocol, CASCADE", "Протокол (если применимо)."),
        ("role_label", "varchar(100)", "Роль в комиссии (председатель, член и т.д.)."),
    ]),
    ("documents_documentsignature", "Универсальные подписи документов. Полиморфная связь через ContentType — одна таблица обслуживает все типы документов.", [
        ("id", "bigint PK", "Первичный ключ."),
        ("document_type_id + document_id", "GenericFK → ContentType", "Полиморфная ссылка на подписываемый документ."),
        ("signer_id", "FK → users_user, CASCADE", "Подписант."),
        ("role_label", "varchar(100)", "Роль при подписании."),
        ("signed_at", "timestamp", "Момент подписания (пусто — ожидание)."),
        ("is_acting_chairman", "boolean", "Признак «и.о. Председателя»."),
        ("sent_for_revision_at", "timestamp", "Отправлено на доработку."),
        ("revision_reason", "text", "Причина возврата."),
    ]),
]

NOTIF_TABLES = [
    ("notifications_notification", "In-app уведомления (колокольчик). Полиморфная привязка к любому объекту системы.", [
        ("id", "bigint PK", "Первичный ключ."),
        ("recipient_id", "FK → users_user, CASCADE", "Получатель."),
        ("notification_type", "varchar(30), choices", "Тип уведомления."),
        ("title", "varchar(255)", "Заголовок."),
        ("body", "text", "Текст."),
        ("related_content_type_id + related_object_id", "GenericFK → ContentType", "Ссылка на связанный объект: заявку, документ, аларм и т.д."),
        ("is_read", "boolean", "Прочитано."),
        ("created_at", "timestamp", "Создано."),
    ]),
    ("notifications_emaillog", "Журнал отправленных email-сообщений.", [
        ("id", "bigint PK", "Первичный ключ."),
        ("recipient_email", "varchar(254)", "Email получателя."),
        ("subject", "varchar(255)", "Тема письма."),
        ("body_preview", "text", "Превью текста."),
        ("status", "varchar(10), choices", "SENT / FAILED."),
        ("sent_at", "timestamp", "Момент отправки."),
        ("related_notification_id", "FK → notifications_notification, SET_NULL", "Связанное in-app уведомление."),
        ("error_message", "text", "Текст ошибки при неудаче."),
    ]),
    ("integrations_synclog", "Журнал синхронизаций с внешними системами, прежде всего с 1С.", [
        ("id", "bigint PK", "Первичный ключ."),
        ("sync_type", "varchar(50)", "Тип синхронизации."),
        ("started_at / finished_at", "timestamp", "Начало и окончание."),
        ("status", "varchar(20): RUNNING / SUCCESS / FAILED", "Статус обмена."),
        ("created_count / updated_count", "int", "Количество созданных и обновлённых записей."),
        ("error_message", "text", "Текст ошибки."),
        ("is_stub", "boolean", "Режим заглушки (интеграция ещё не активирована)."),
    ]),
]

ALL_SECTIONS = [
    ("Организационная структура и права доступа", ORG_TABLES),
    ("Нормативно-справочная информация", REF_TABLES),
    ("Складской учёт", STOCK_TABLES),
    ("Заявочный процесс", REQUEST_TABLES),
    ("Документооборот", DOC_TABLES),
    ("Уведомления и интеграции", NOTIF_TABLES),
]
